-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트를 출력


WITH CAR_DATE AS 
(
    SELECT A.CAR_ID, A.START_DATE, A.END_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
        JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
    WHERE A.END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
),
CAR_FEE AS 
(
    SELECT 
        A.CAR_ID AS CAR_ID, 
        A.CAR_TYPE AS CAR_TYPE,
        TRUNC(A.DAILY_FEE * 30 * (100 - B.DISCOUNT_RATE) / 100) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR A
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B ON A.CAR_TYPE = B.CAR_TYPE
    WHERE B.DURATION_TYPE = '30일 이상' 
)

SELECT 
    A.CAR_ID AS CAR_ID, 
    A.CAR_TYPE AS CAR_TYPE, 
    A.FEE AS FEE
FROM CAR_FEE A
WHERE CAR_TYPE IN ('세단', 'SUV') 
    AND A.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_DATE)
    AND A.FEE >= 500000 AND A.FEE < 2000000
ORDER BY A.FEE DESC, A.CAR_TYPE, A.CAR_ID DESC

