-- USER_INFO 테이블과 ONLINE_SALE 테이블에서 년, 월, 성별 별로 상품을 구매한 회원수를 집계

SELECT 
    TO_CHAR(A.SALES_DATE, 'YYYY') AS YEAR,
    TO_NUMBER(TO_CHAR(A.SALES_DATE, 'MM')) AS MONTH,
    B.GENDER AS GENDER,
    COUNT(DISTINCT B.USER_ID) AS USERS
FROM ONLINE_SALE A
    JOIN USER_INFO B ON A.USER_ID = B.USER_ID
WHERE B.GENDER IS NOT NULL
GROUP BY 
    TO_CHAR(A.SALES_DATE, 'YYYY'), 
    TO_NUMBER(TO_CHAR(A.SALES_DATE, 'MM')), 
    B.GENDER 
ORDER BY YEAR, MONTH, GENDER