SELECT
    TO_CHAR(SALES_DATE, 'YYYY') AS YEAR,
    TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) AS MONTH,
    U.GENDER,
    COUNT(DISTINCT U.USER_ID) AS USERS
FROM ONLINE_SALE S
JOIN USER_INFO U ON S.USER_ID = U.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY
    TO_CHAR(SALES_DATE, 'YYYY'),
    TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')),
    U.GENDER
ORDER BY
    YEAR, MONTH, GENDER;