-- 물고기의 종류 별 물고기의 이름과 잡은 수 출력
SELECT 
    COUNT(*) AS FISH_COUNT,
    B.FISH_NAME AS FISH_NAME
FROM FISH_INFO A 
    JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY B.FISH_NAME 
ORDER BY FISH_COUNT DESC