-- 2021년에 가입한 전체 회원들 중 상품을 구매한 회원수와 상품을 구매한 회원의 비율(=2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수)을 년, 월 별로 출력

WITH USER_TMP AS 
(SELECT USER_ID, JOINED  
FROM USER_INFO 
WHERE TO_CHAR(JOINED, 'YYYY') = '2021' 
)

SELECT 
    TO_CHAR(B.SALES_DATE, 'YYYY') AS YEAR,
    TO_NUMBER(TO_CHAR(B.SALES_DATE, 'MM')) AS MONTH,
    COUNT(DISTINCT B.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT B.USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM USER_TMP), 1) AS PUCHASED_RATIO
FROM USER_TMP A
    JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
GROUP BY 
    TO_CHAR(B.SALES_DATE, 'YYYY'),
    TO_NUMBER(TO_CHAR(B.SALES_DATE, 'MM'))
ORDER BY YEAR, MONTH