WITH HISTORY_TMP AS 
(
SELECT B.HISTORY_ID, A.DAILY_FEE, TO_NUMBER(B.END_DATE - B.START_DATE) + 1 AS DAY 
FROM CAR_RENTAL_COMPANY_CAR A
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE = '트럭'
),
RULE_TMP AS (
SELECT 
    TO_NUMBER(SUBSTR(DURATION_TYPE, 0, INSTR(DURATION_TYPE, '일') - 1)) AS DURATION, 
    DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE CAR_TYPE = '트럭'
)

SELECT 
    A.HISTORY_ID AS HISTORY_ID,
    TRUNC(A.DAILY_FEE * A.DAY * (100 - NVL(MAX(B.DISCOUNT_RATE), 0)) / 100) AS FEE
FROM HISTORY_TMP A 
    LEFT JOIN RULE_TMP B 
    ON A.DAY >= B.DURATION
GROUP BY A.HISTORY_ID, A.DAILY_FEE, A.DAY
ORDER BY FEE DESC, HISTORY_ID DESC;










