WITH A AS 
(SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER 
FROM FIRST_HALF
GROUP BY FLAVOR),
B AS 
(SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER 
FROM JULY
GROUP BY FLAVOR)

SELECT A.FLAVOR
FROM A JOIN B ON A.FLAVOR = B.FLAVOR
ORDER BY A.TOTAL_ORDER + B.TOTAL_ORDER DESC
FETCH FIRST 3 ROWS ONLY;