SELECT
  A.HOUR,
  COUNT(B.DATETIME) AS COUNT
FROM
  (SELECT LEVEL - 1 AS HOUR
   FROM DUAL
   CONNECT BY LEVEL <= 24) A
  LEFT OUTER JOIN ANIMAL_OUTS B
    ON TO_NUMBER(TO_CHAR(B.DATETIME, 'HH24')) = A.HOUR
GROUP BY A.HOUR
ORDER BY A.HOUR;
