-- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회

-- 1. 리뷰를 가장 많이 작성한 회원 찾기
SELECT B.MEMBER_NAME, A.REVIEW_TEXT, A.REVIEW_DATE
FROM
    (SELECT A.MEMBER_ID, A.REVIEW_TEXT, TO_CHAR(A.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
    FROM REST_REVIEW A JOIN
        (SELECT RANK() OVER (ORDER BY COUNT(MEMBER_ID) DESC) AS RANK, MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID) B ON A.MEMBER_ID = B.MEMBER_ID
    WHERE RANK = 1) A JOIN MEMBER_PROFILE B ON A.MEMBER_ID = B.MEMBER_ID
ORDER BY A.REVIEW_DATE, A.REVIEW_TEXT;