-- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회

WITH REVIEW_COUNT AS 
(
    SELECT MEMBER_ID, COUNT(MEMBER_ID) AS COUNT, RANK() OVER (ORDER BY COUNT(*) DESC) AS RANKING
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)

SELECT 
    B.MEMBER_NAME AS MEMBER_NAME, 
    A.REVIEW_TEXT AS REVIEW_TEXT, 
    TO_CHAR(A.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM REST_REVIEW A 
    JOIN MEMBER_PROFILE B ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID IN (SELECT MEMBER_ID FROM REVIEW_COUNT WHERE RANKING = 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT