-- 보호 시작일보다 입양일이 더 빠른 동물의 아이디와 이름 조회
-- ANIMAL_INS보다 ANIMAL_OUTS가 더 빨라야 함

SELECT A.ANIMAL_ID, A.NAME 
FROM ANIMAL_INS A JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.DATETIME > B.DATETIME
ORDER BY A.DATETIME