SELECT 
    SUM(C.SCORE) AS SCORE,
    A.EMP_NO, 
    A.EMP_NAME, 
    A.POSITION, 
    A.EMAIL
FROM HR_EMPLOYEES A
JOIN HR_GRADE C ON A.EMP_NO = C.EMP_NO
WHERE C.YEAR = '2022'
GROUP BY A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
HAVING SCORE = (
    SELECT MAX(SUM_SCORE)
    FROM (
        SELECT EMP_NO, SUM(SCORE) AS SUM_SCORE
        FROM HR_GRADE
        WHERE YEAR = '2022'
        GROUP BY EMP_NO
    ) AS SCORE_TABLE
)