-- 식품분류별로 가격이 제일 비싼 식품의 분류, 가격, 이름을 조회
SELECT B.CATEGORY, B.MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A, (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY) B
WHERE A.CATEGORY = B.CATEGORY AND A.PRICE = B.MAX_PRICE 
ORDER BY A.PRICE DESC



